apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    component: elk
    role: elasticsearch
spec:
  selector:
    component: elk
    role: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
  - name: elasticsearch-https
    port: 9300
    protocol: TCP
