apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  namespace: default
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  selector:
    component: elk
    role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elk
      containers:
      - name: logstash
        image: logstash
        command: ['logstash', 'agent']
        args: ['-f', '/config-dir/logstash-config/logstash.conf']
        ports:
        - containerPort: 5043
          name: lumberjack
          protocol: TCP
        - containerPort: 5000
          name: tcp
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config-dir
        #volumeMounts:
        #- mountPath: /certs
        #  name: certs
      volumes:
      - name: storage
        source:
          emptyDir: {}
      - name: config
        gitRepo:
          repository: https://github.com/ubc/logstash-config.git
          revision: master
      #- name: certs
      #  source:
      #    hostPath:
      #      path: /tmp
